openapi: 3.0.0
info:
  title: SEC XBRL API
  version: 2.0.0
  description: Get financial data extracted from SEC XBRL instance documents and filings.

servers:
  - url: https://sec-api-backend.onrender.com

paths:
  /get_multiple_xbrl:
    get:
      summary: Get latest 2 10-Ks and 4 10-Qs XBRL instance documents
      parameters:
        - in: query
          name: cik
          required: true
          schema:
            type: string
          description: 10-digit Central Index Key (CIK) of the company
      responses:
        '200':
          description: Successfully fetched multiple XBRL documents
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    company_cik:
                      type: string
                    filing_date:
                      type: string
                    accession_number:
                      type: string
                    form_type:
                      type: string
                    xbrl_url:
                      type: string
                    xbrl_text:
                      type: string
        '404':
          description: No filings found
        '500':
          description: Internal server error

  /financials:
    get:
      summary: Get SEC financials and extracted metrics for trade-credit analysis
      parameters:
        - in: query
          name: query
          required: true
          schema:
            type: string
          description: Company name (e.g., "Airbnb", "Snap", "Uber")
      responses:
        '200':
          description: Successfully fetched financial summary
          content:
            application/json:
              schema:
                type: object
                properties:
                  company:
                    type: string
                  cik:
                    type: string
                  historical_annuals:
                    type: array
                    items:
                      type: object
                      properties:
                        formType:
                          type: string
                        filingDate:
                          type: string
                        fiscalYear:
                          type: string
                        xbrl_text:
                          type: string
                        extracted:
                          type: object
        '400':
          description: Missing query parameter
        '500':
          description: Internal server error
